<?php

namespace App\Http\Controllers;

use App\Models\TelegramLinkCode;
use App\Models\TelegramConnection;
use App\Models\InventoryIncreaseRequest;
use App\Models\Notification;
use App\Models\DepositRequest;
use App\Models\Transaction;
use App\Models\WalletTransaction;
use App\Models\GoldLedger;
use App\Models\SilverLedger;
use App\Models\SilverDeliveryRequest;
use App\Models\TradeRoomOffer;
use App\Models\ActivityLog;
use App\Models\AssetCollateralRequest;
use App\Models\Setting;
use App\Services\PriceService;
use App\Services\TradeRoomExpiryService;
use App\Models\User;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class TelegramMembershipController extends Controller
{
    private function authorize(Request $request): void
    {
        $token = (string) config('services.telegram.link_api_token');

        abort_unless($token !== '' && hash_equals($token, (string) $request->bearerToken()), 401);
    }

    public function link(Request $request): JsonResponse
    {
        return $this->connect($request);
    }

    /**
     * Consumes a short-lived code generated by the signed-in website user.
     * This endpoint is called only by the Telegram bot, using its shared secret.
     */
    public function connect(Request $request): JsonResponse
    {
        $this->authorize($request);
        $data = $request->validate([
            'code' => ['required', 'string', 'digits:6'],
            'telegram_user_id' => ['required', 'integer', 'min:1'],
            'telegram_chat_id' => ['required', 'integer'],
            'telegram_username' => ['nullable', 'string', 'max:255'],
        ]);

        $user = DB::transaction(function () use ($data) {
            $code = TelegramLinkCode::query()
                ->where('code_hash', hash('sha256', $data['code']))
                ->whereNull('used_at')
                ->where('expires_at', '>', now())
                ->lockForUpdate()
                ->first();

            abort_unless($code, 422, 'کد اتصال نامعتبر یا منقضی شده است.');
            $user = User::query()->lockForUpdate()->findOrFail($code->user_id);

            $conflict = TelegramConnection::query()
                ->where(function ($query) use ($data) {
                    $query->where('telegram_user_id', (string) $data['telegram_user_id'])
                        ->orWhere('telegram_chat_id', (string) $data['telegram_chat_id']);
                })
                ->where('user_id', '!=', $user->id)
                ->exists();
            abort_if($conflict, 422, 'این حساب تلگرام به کاربر دیگری متصل است.');

            TelegramConnection::updateOrCreate(
                ['user_id' => $user->id],
                [
                    'telegram_user_id' => (string) $data['telegram_user_id'],
                    'telegram_chat_id' => (string) $data['telegram_chat_id'],
                    'telegram_username' => $data['telegram_username'] ?? null,
                    'connected_at' => now(),
                ],
            );

            // Existing bot endpoints still identify a member by chat ID.
            $user->update(['telegram_chat_id' => (string) $data['telegram_chat_id']]);
            $code->update(['used_at' => now()]);

            return $user;
        });

        return response()->json($this->membershipPayload($user));
    }

    public function member(Request $request): JsonResponse
    {
        $this->authorize($request);
        $data = $request->validate(['telegram_chat_id' => ['required', 'string', 'max:32']]);
        $user = User::query()->where('telegram_chat_id', $data['telegram_chat_id'])->first();

        if (! $user) {
            return response()->json(['linked' => false, 'vip' => false, 'membership_level' => 0, 'membership_status' => 'none']);
        }

        return response()->json($this->membershipPayload($user));
    }

    public function inventoryIncrease(Request $request): JsonResponse
    {
        $this->authorize($request);
        $data = $request->validate([
            'telegram_chat_id' => ['required', 'string', 'max:32'],
            'item' => ['required', 'in:gold,silver_999,silver_995,full_coin,half_coin,quarter_coin'],
            'quantity' => ['required', 'numeric', 'min:0.0001', 'max:1000000'],
            'note' => ['nullable', 'string', 'max:500'],
            'receipt' => ['nullable', 'image', 'max:5120'],
        ]);

        $user = User::query()->where('telegram_chat_id', $data['telegram_chat_id'])->first();
        abort_unless($user && $user->isVipMember(), 403, 'عضویت ویژه فعال نیست.');

        $items = [
            'gold' => ['metal' => 'gold', 'purity' => '', 'label' => 'طلا', 'unit' => 'گرم'],
            'silver_999' => ['metal' => 'silver', 'purity' => '999', 'label' => 'نقره ۹۹۹/۹', 'unit' => 'گرم'],
            'silver_995' => ['metal' => 'silver', 'purity' => '995', 'label' => 'نقره ۹۹۵', 'unit' => 'گرم'],
            'full_coin' => ['metal' => 'coin', 'purity' => 'full', 'label' => 'سکه تمام', 'unit' => 'عدد'],
            'half_coin' => ['metal' => 'coin', 'purity' => 'half', 'label' => 'نیم‌سکه', 'unit' => 'عدد'],
            'quarter_coin' => ['metal' => 'coin', 'purity' => 'quarter', 'label' => 'ربع‌سکه', 'unit' => 'عدد'],
        ];
        $item = $items[$data['item']];
        abort_if($item['unit'] === 'عدد' && floor((float) $data['quantity']) !== (float) $data['quantity'], 422, 'تعداد سکه باید عدد صحیح باشد.');

        $increase = InventoryIncreaseRequest::create([
            'user_id' => $user->id,
            'metal' => $item['metal'],
            'purity' => $item['purity'],
            'grams' => $data['quantity'],
            'note' => $data['note'] ?? null,
            'receipt_path' => $request->hasFile('receipt') ? $request->file('receipt')->store('receipts/telegram-inventory', 'public') : null,
            'source' => 'telegram_bot',
        ]);

        User::where('is_admin', true)->each(fn (User $admin) => Notification::create([
            'user_id' => $admin->id,
            'title' => "درخواست افزایش موجودی ربات — {$user->name}",
            'body' => "{$increase->grams} {$item['unit']} {$item['label']}",
            'type' => 'system',
        ]));

        return response()->json(['id' => $increase->id, 'label' => $item['label'], 'unit' => $item['unit']]);
    }

    public function overview(Request $request, PriceService $prices): JsonResponse
    {
        $this->authorize($request);
        $user = $this->vipUserForChat($request);

        return response()->json([
            'wallet_balance' => $user->walletBalance(),
            'assets' => [
                'gold' => $user->goldBalance(),
                'silver_999' => $user->silverBalance('999'),
                'silver_995' => $user->silverBalance('995'),
            ],
            'prices' => $prices->all(),
            'trades' => Transaction::query()->where('user_id', $user->id)->latest()->take(20)->get(['id', 'type', 'item_label', 'quantity', 'total', 'status', 'created_at']),
            'deposits' => DepositRequest::query()->where('user_id', $user->id)->latest()->take(20)->get(['id', 'amount', 'note', 'status', 'admin_note', 'created_at']),
            'asset_collateral_available' => $this->availableCollateralAmount($user),
        ]);
    }

    public function deposit(Request $request): JsonResponse
    {
        $this->authorize($request);
        $user = $this->vipUserForChat($request);
        $data = $request->validate([
            'amount' => ['required', 'integer', 'min:1000'],
            'note' => ['nullable', 'string', 'max:200'],
            'receipt' => ['nullable', 'image', 'max:5120'],
        ]);

        $deposit = DepositRequest::create([
            'user_id' => $user->id,
            'amount' => $data['amount'],
            'source' => 'telegram_bot',
            'note' => $data['note'] ?? 'درخواست ثبت‌شده از ربات تلگرام',
            'receipt_path' => $request->hasFile('receipt') ? $request->file('receipt')->store('receipts/telegram', 'public') : null,
            'status' => 'pending',
        ]);
        User::where('is_admin', true)->each(fn (User $admin) => Notification::create([
            'user_id' => $admin->id,
            'title' => "درخواست افزایش موجودی ربات — {$user->name}",
            'body' => number_format($deposit->amount).' تومان — در انتظار بررسی',
            'type' => 'wallet',
        ]));

        return response()->json(['id' => $deposit->id, 'status' => $deposit->status], 201);
    }

    public function trade(Request $request, PriceService $prices): JsonResponse
    {
        $this->authorize($request);
        $user = $this->vipUserForChat($request);
        $data = $request->validate([
            'side' => ['required', 'in:buy,sell'],
            'unit' => ['required', 'in:mesghal,gram'],
            'quantity' => ['required', 'numeric', 'min:0.001'],
        ]);

        $item = $data['unit'] === 'mesghal' ? 'mithqal' : 'geram';
        $label = $data['unit'] === 'mesghal' ? 'مثقال طلا' : 'گرم طلا';
        $quantity = (float) $data['quantity'];
        $grams = $data['unit'] === 'mesghal' ? round($quantity * (float) env('MITHQAL_GRAMS', 4.3318), 4) : $quantity;
        abort_if($grams < 10, 422, 'حداقل مقدار معامله ۱۰ گرم است.');
        $price = (float) data_get($prices->all(), "gold.{$item}");
        abort_unless($price > 0, 422, 'قیمت در دسترس نیست.');
        $total = (int) round($quantity * $price);

        $transaction = DB::transaction(function () use ($user, $data, $item, $label, $quantity, $grams, $price, $total) {
            $user = User::query()->lockForUpdate()->findOrFail($user->id);
            if ($data['side'] === 'buy') {
                abort_if($user->walletBalance() < $total, 422, 'موجودی کیف پول کافی نیست.');
                WalletTransaction::create(['user_id' => $user->id, 'amount' => -$total, 'type' => 'withdraw', 'description' => "خرید {$label} از ربات"]);
                GoldLedger::create(['user_id' => $user->id, 'grams' => $grams, 'type' => 'purchase', 'description' => "خرید {$label} از ربات"]);
            } else {
                abort_if($user->goldBalance() < $grams, 422, 'موجودی طلای شما کافی نیست.');
                WalletTransaction::create(['user_id' => $user->id, 'amount' => $total, 'type' => 'deposit', 'description' => "فروش {$label} از ربات"]);
                GoldLedger::create(['user_id' => $user->id, 'grams' => -$grams, 'type' => 'sale', 'description' => "فروش {$label} از ربات"]);
            }

            return Transaction::create([
                'user_id' => $user->id,
                'type' => $data['side'],
                'item' => $item,
                'item_label' => $label,
                'quantity' => $quantity,
                'price_per_unit' => (int) $price,
                'total' => $total,
                'status' => 'active',
                'admin_note' => 'ثبت‌شده از ربات تلگرام',
            ]);
        });
        ActivityLog::record('telegram_trade', 'trade', "ثبت {$data['side']} {$label} از ربات", $user->id);

        return response()->json($transaction, 201);
    }

    /** فهرست سفارش‌های باز اتاق معاملاتی، بدون اطلاعات هویتی طرفین. */
    public function tradeRoomOffers(Request $request, TradeRoomExpiryService $expiry): JsonResponse
    {
        $this->authorize($request);
        $user = $this->vipUserForChat($request);
        $expiry->expireOpenOffers();

        $data = $request->validate([
            'mine' => ['nullable'],
            'status' => ['nullable'],
        ]);
        $mine = filter_var($data['mine'] ?? false, FILTER_VALIDATE_BOOL);
        $statuses = collect((array) ($data['status'] ?? []))
            ->flatMap(fn ($status) => is_string($status) ? explode(',', $status) : [$status])
            ->map(fn ($status) => match (strtolower(trim((string) $status))) {
                'active', 'available', 'published' => 'open',
                'accepted' => 'completed',
                default => strtolower(trim((string) $status)),
            })
            ->filter()
            ->values()
            ->all();

        $query = TradeRoomOffer::query()->orderByDesc('created_at');
        if ($mine) {
            $query->where(fn ($query) => $query->where('user_id', $user->id)->orWhere('counterparty_id', $user->id));
        } else {
            $query->where('status', 'open');
        }
        if ($statuses) {
            $query->whereIn('status', $statuses);
        }

        $offers = $query->limit(100)->get()
            ->map(fn (TradeRoomOffer $offer) => [
                'id' => $offer->id,
                'asset' => $this->roomAsset($offer),
                'side' => $offer->side,
                'quantity' => (float) $offer->grams,
                'unit_price' => (int) $offer->price_per_gram,
                'unit' => $offer->metal === 'coin' ? 'piece' : 'gram',
                'total' => $offer->total(),
                'status' => $offer->status,
                'source' => $offer->source,
                'is_from_bot' => $offer->source === 'telegram_bot',
                'is_mine' => $offer->user_id === $user->id,
                'is_counterparty' => $offer->counterparty_id === $user->id,
                'created_at' => $offer->created_at?->toIso8601String(),
                'completed_at' => $offer->completed_at?->toIso8601String(),
            ]);

        return response()->json(['offers' => $offers]);
    }

    /** ثبت پیشنهاد خرید یا فروش ربات در اتاق معاملاتی با رزرو دارایی. */
    public function tradeRoomOffer(Request $request): JsonResponse
    {
        $this->authorize($request);
        $user = $this->vipUserForChat($request);
        $data = $request->validate([
            'asset' => ['required', 'in:gold,silver_999,silver_995,full_coin,half_coin,quarter_coin'],
            'side' => ['required', 'in:buy,sell'],
            'unit' => ['required', 'in:gram,mesghal,piece'],
            'quantity' => ['required', 'numeric', 'min:0.0001', 'max:1000000'],
            'unit_price' => ['required', 'integer', 'min:1'],
        ]);

        $assets = [
            'gold' => ['metal' => 'gold', 'purity' => '', 'item' => null],
            'silver_999' => ['metal' => 'silver', 'purity' => '999', 'item' => null],
            'silver_995' => ['metal' => 'silver', 'purity' => '995', 'item' => null],
            'full_coin' => ['metal' => 'coin', 'purity' => 'full', 'item' => 'bahar'],
            'half_coin' => ['metal' => 'coin', 'purity' => 'half', 'item' => 'nim'],
            'quarter_coin' => ['metal' => 'coin', 'purity' => 'quarter', 'item' => 'rob'],
        ];
        $asset = $assets[$data['asset']];
        $isCoin = $asset['metal'] === 'coin';
        abort_if($isCoin && $data['unit'] !== 'piece', 422, 'واحد سکه باید piece باشد.');
        abort_if(! $isCoin && $data['unit'] === 'piece', 422, 'واحد طلا و نقره باید gram یا mesghal باشد.');

        $factor = (float) env('MITHQAL_GRAMS', 4.3318);
        $quantity = (float) $data['quantity'];
        $amount = $data['unit'] === 'mesghal' ? round($quantity * $factor, 4) : $quantity;
        $price = $data['unit'] === 'mesghal' ? (int) round($data['unit_price'] / $factor) : (int) $data['unit_price'];
        abort_if($isCoin && floor($amount) !== $amount, 422, 'تعداد سکه باید صحیح باشد.');
        abort_if($asset['metal'] === 'silver' && $amount < 100, 422, 'حداقل سفارش اتاق معاملاتی ۱۰۰ گرم است.');
        $total = (int) round($amount * $price);

        $offer = DB::transaction(function () use ($user, $asset, $isCoin, $data, $amount, $price, $total) {
            $lockedUser = User::query()->lockForUpdate()->findOrFail($user->id);
            if ($data['side'] === 'buy') {
                $wallet = $lockedUser->walletBalance();
                $missing = max(0, $total - $wallet);
                abort_if($missing > 0 && $this->availableCollateralAmount($lockedUser) < $missing, 422, 'موجودی کیف پول یا اعتبار بیعانه دارایی کافی نیست.');
            } elseif ($isCoin) {
                $held = (float) Transaction::query()->where('user_id', $lockedUser->id)->where('item', $asset['item'])->where('status', 'active')->where('type', 'buy')->sum('quantity')
                    - (float) Transaction::query()->where('user_id', $lockedUser->id)->where('item', $asset['item'])->where('status', 'active')->where('type', 'sell')->sum('quantity');
                abort_if($held < $amount, 422, 'موجودی سکه کافی نیست.');
            } else {
                $balance = $asset['metal'] === 'gold' ? $lockedUser->goldBalance() : $lockedUser->silverBalance($asset['purity']);
                abort_if($balance < $amount, 422, 'موجودی انبار کافی نیست.');
            }

            $walletReserve = $data['side'] === 'buy' ? min($lockedUser->walletBalance(), $total) : 0;
            $collateralReserve = $data['side'] === 'buy' ? $total - $walletReserve : 0;
            $offer = TradeRoomOffer::create([
                'user_id' => $lockedUser->id, 'source' => 'telegram_bot',
                'metal' => $asset['metal'], 'item' => $asset['item'],
                'side' => $data['side'], 'purity' => $asset['purity'], 'grams' => $amount,
                'price_per_gram' => $price, 'wallet_reserved_amount' => $walletReserve,
                'collateral_reserved_amount' => $collateralReserve, 'status' => 'open',
            ]);
            if ($data['side'] === 'buy') {
                if ($walletReserve > 0) {
                    WalletTransaction::create(['user_id' => $lockedUser->id, 'amount' => -$walletReserve, 'type' => 'withdraw', 'description' => "رزرو پیشنهاد خرید ربات #{$offer->id}"]);
                }
                $this->reserveCollateral($lockedUser, $collateralReserve);
            } elseif (! $isCoin) {
                $ledger = $asset['metal'] === 'gold' ? GoldLedger::class : SilverLedger::class;
                $values = ['user_id' => $lockedUser->id, 'grams' => -$amount, 'type' => 'offer_escrow', 'reference_type' => TradeRoomOffer::class, 'reference_id' => $offer->id, 'description' => "رزرو پیشنهاد فروش ربات #{$offer->id}"];
                if ($ledger === SilverLedger::class) $values['purity'] = $asset['purity'];
                $ledger::create($values);
            }
            return $offer;
        });

        ActivityLog::record('telegram_room_offer', 'trade', "ثبت پیشنهاد {$data['side']} در اتاق معاملاتی #{$offer->id}", $user->id);
        return response()->json(['id' => $offer->id, 'status' => $offer->status, 'total' => $offer->total()], 201);
    }

    /** Accept a room offer for the Telegram bot, using the same atomic wallet
     * and commission path as the website trade-room action. */
    public function tradeRoomAccept(Request $request, int $id)
    {
        $this->authorize($request);
        $user = $this->vipUserForChat($request);
        $request->merge(['grams' => $request->input('quantity')]);
        $request->setUserResolver(fn () => $user);

        return app(TradeRoomController::class)->accept($request, $id);
    }

    public function assetCollateral(Request $request): JsonResponse
    {
        $this->authorize($request);
        $user = $this->vipUserForChat($request);
        $data = $request->validate([
            'asset' => ['required', 'in:gold,silver_999,silver_995,full_coin,half_coin,quarter_coin'],
            'quantity' => ['required', 'numeric', 'min:0.0001', 'max:1000000'],
            'note' => ['nullable', 'string', 'max:500'],
        ]);

        $collateral = AssetCollateralRequest::create([
            'user_id' => $user->id,
            'asset' => $data['asset'],
            'quantity' => $data['quantity'],
            'status' => 'pending',
            'note' => $data['note'] ?? null,
            'source' => 'telegram_bot',
        ]);

        User::where('is_admin', true)->each(fn (User $admin) => Notification::create([
            'user_id' => $admin->id,
            'title' => "درخواست بیعانه دارایی ربات — {$user->name}",
            'body' => $data['quantity'].' '.$data['asset'].' — در انتظار تعیین سقف معامله',
            'type' => 'system',
        ]));

        return response()->json([
            'id' => $collateral->id,
            'status' => $collateral->status,
            'message' => 'درخواست بیعانه دارایی ثبت شد و در سایت بررسی می‌شود.',
        ], 201);
    }

    public function delivery(Request $request): JsonResponse
    {
        $this->authorize($request);
        $user = $this->vipUserForChat($request);
        $data = $request->validate([
            'asset' => ['required', 'in:gold,silver_999,silver_995'],
            'quantity' => ['required', 'numeric', 'min:1'],
            'recipient_name' => ['required', 'string', 'max:100'],
            'phone' => ['required', 'string', 'max:20'],
            'delivery_method' => ['required', 'in:address,pickup'],
            'address' => ['required_if:delivery_method,address', 'nullable', 'string', 'max:500'],
            'postal_code' => ['required_if:delivery_method,address', 'nullable', 'string', 'max:20'],
        ]);
        $metal = $data['asset'] === 'gold' ? 'gold' : 'silver';
        $purity = $metal === 'gold' ? '' : str_replace('silver_', '', $data['asset']);
        $grams = (float) $data['quantity'];
        $balance = $metal === 'gold' ? $user->goldBalance() : $user->silverBalance($purity);
        abort_if($balance < $grams, 422, 'موجودی انبار کافی نیست.');

        $delivery = DB::transaction(function () use ($user, $data, $metal, $purity, $grams) {
            $delivery = SilverDeliveryRequest::create([
                'user_id' => $user->id, 'metal' => $metal, 'purity' => $purity, 'grams' => $grams,
                'recipient_name' => $data['recipient_name'], 'phone' => $data['phone'],
                'delivery_method' => $data['delivery_method'], 'address' => $data['delivery_method'] === 'pickup' ? 'تحویل حضوری از فروشگاه' : $data['address'],
                'postal_code' => $data['delivery_method'] === 'pickup' ? null : $data['postal_code'], 'source' => 'telegram_bot', 'status' => 'pending',
            ]);
            $ledger = $metal === 'gold' ? GoldLedger::class : SilverLedger::class;
            $values = ['user_id' => $user->id, 'grams' => -$grams, 'type' => 'delivery', 'reference_type' => SilverDeliveryRequest::class, 'reference_id' => $delivery->id, 'description' => "درخواست تحویل ربات #{$delivery->id}"];
            if ($ledger === SilverLedger::class) $values['purity'] = $purity;
            $ledger::create($values);
            return $delivery;
        });
        return response()->json(['id' => $delivery->id, 'status' => $delivery->status], 201);
    }

    public function deliveryStatus(Request $request, int $id): JsonResponse
    {
        $this->authorize($request);
        $user = $this->vipUserForChat($request);
        $delivery = SilverDeliveryRequest::query()->where('user_id', $user->id)->findOrFail($id);
        return response()->json(['id' => $delivery->id, 'status' => $delivery->status, 'admin_note' => $delivery->admin_note, 'updated_at' => $delivery->updated_at?->toIso8601String()]);
    }

    public function receipt(Request $request): JsonResponse
    {
        $this->authorize($request);
        $user = $this->vipUserForChat($request);
        $data = $request->validate([
            'deposit_id' => ['required', 'integer'],
            'receipt' => ['required', 'image', 'max:5120'],
        ]);
        $deposit = DepositRequest::query()->where('user_id', $user->id)->where('status', 'pending')->findOrFail($data['deposit_id']);
        $deposit->update(['receipt_path' => $request->file('receipt')->store('receipts/telegram', 'public')]);

        return response()->json(['id' => $deposit->id, 'receipt_uploaded' => true]);
    }

    private function vipUserForChat(Request $request): User
    {
        $chatId = $request->validate(['telegram_chat_id' => ['required', 'string', 'max:32']])['telegram_chat_id'];
        $user = User::query()->where('telegram_chat_id', $chatId)->first();
        abort_unless($user && $user->isVipMember(), 403, 'عضویت ویژه فعال نیست.');

        return $user;
    }

    private function roomAsset(TradeRoomOffer $offer): string
    {
        if ($offer->metal === 'gold') return 'gold';
        if ($offer->metal === 'silver') return 'silver_'.$offer->purity;

        return ['bahar' => 'full_coin', 'nim' => 'half_coin', 'rob' => 'quarter_coin'][$offer->item] ?? 'coin';
    }

    private function membershipPayload(User $user): array
    {
        return [
            'linked' => true,
            'vip' => $user->isVipMember(),
            'user_id' => $user->id,
            'name' => $user->name,
            'phone' => $user->phone,
            'membership_level' => $user->membership_level,
            'membership_status' => $user->membership_status,
            'trade_room_commission_percent' => (float) Setting::get('trade_room_commission_percent', 0.1),
            'asset_collateral_available' => $this->availableCollateralAmount($user),
        ];
    }

    private function availableCollateralAmount(User $user): int
    {
        return (int) AssetCollateralRequest::query()
            ->where('user_id', $user->id)
            ->where('status', 'approved')
            ->get()
            ->sum(fn (AssetCollateralRequest $collateral) => $collateral->availableAmount());
    }

    private function reserveCollateral(User $user, int $amount): void
    {
        if ($amount <= 0) {
            return;
        }

        $remaining = $amount;
        AssetCollateralRequest::query()
            ->where('user_id', $user->id)
            ->where('status', 'approved')
            ->whereColumn('used_amount', '<', 'trade_limit_amount')
            ->lockForUpdate()
            ->orderBy('id')
            ->get()
            ->each(function (AssetCollateralRequest $collateral) use (&$remaining) {
                if ($remaining <= 0) {
                    return;
                }

                $use = min($remaining, $collateral->availableAmount());
                $collateral->increment('used_amount', $use);
                $remaining -= $use;
            });

        abort_if($remaining > 0, 422, 'اعتبار بیعانه دارایی کافی نیست.');
    }
}
